title: Mars Blog
email: marswong618@gmail.com
description: The utopia of Mars
motto: Le vent se lève, il faut tenter de vivre
baseurl: ""
url: "https://mars.js.org"

author:
  name: 'Mars Wong'
  email: marswong618@gmail.com
  url: https://mars.js.org
  resume: https://mars.js.org
  facebook: https://www.facebook.com/maaarswong
  twitter: https://twitter.com/maaarswong
  github: https://github.com/marswong

paginate: 3
comments: false
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink : /:title/
